In [206]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf


# if __name__ == "__main__":


#     dataset_df = pd.read_csv('updated_data_removed_outliers.csv')

#     feature_medications = dataset_df.iloc[:, 27:50]
#     print(feature_medications.columns)
#     for label in feature_medications.columns:
        
#     # for index, label in enumerate(dataset_df.columns):
#     #     print(f"[{index}] {label}")

In [2]:
dataset_df = pd.read_csv('updated_data_removed_outliers.csv')

In [3]:
possible_diagnosis = [
    "circulatory",
    "respiratory",
    "digestive",
    "diabetes",
    "injury",
    "musculoskeletal",
    "genitourinary",
    "neoplasms",
    "other"
]

new_df = pd.DataFrame()
feature_medications = dataset_df.iloc[:, 27:50]


In [4]:
for label in feature_medications:
    new_df[label] = dataset_df[f'{label}_numeric']

In [5]:
for diagnosis in possible_diagnosis:
    new_df[diagnosis] = dataset_df[diagnosis]

In [6]:
print(new_df.head())

   metformin  repaglinide  nateglinide  chlorpropamide  glimepiride  \
0          0            0            0               0            0   
1          0            0            0               0            0   
2          0            0            0               0            0   
3          0            0            0               0            0   
4          0            0            0               0            0   

   acetohexamide  glipizide  glyburide  tolbutamide  pioglitazone  ...  \
0              0          0          0            0             0  ...   
1              0          0          0            0             0  ...   
2              0          2          0            0             0  ...   
3              0          0          0            0             0  ...   
4              0          2          0            0             0  ...   

   metformin.pioglitazone  circulatory  respiratory  digestive  diabetes  \
0                       0          0.0          0.0 

In [20]:
predictors = np.array(new_df)

In [8]:
for label in dataset_df.columns:
    print(label)

Unnamed: 0
X
Unnamed..0
encounter_id
patient_nbr
race
gender
age
weight
admission_type_id
discharge_disposition_id
admission_source_id
time_in_hospital
payer_code
medical_specialty
num_lab_procedures
num_procedures
num_medications
number_outpatient
number_emergency
number_inpatient
diag_1
diag_2
diag_3
number_diagnoses
max_glu_serum
A1Cresult
metformin
repaglinide
nateglinide
chlorpropamide
glimepiride
acetohexamide
glipizide
glyburide
tolbutamide
pioglitazone
rosiglitazone
acarbose
miglitol
troglitazone
tolazamide
examide
citoglipton
insulin
glyburide.metformin
glipizide.metformin
glimepiride.pioglitazone
metformin.rosiglitazone
metformin.pioglitazone
change
diabetesMed
readmitted
circulatory
respiratory
digestive
diabetes
injury
musculoskeletal
genitourinary
neoplasms
other
diag_1_binned
diag_2_binned
diag_3_binned
new_ages
age_numeric_z
number_diagnoses_z
metformin_numeric
metformin_numeric_z
repaglinide_numeric
repaglinide_numeric_z
nateglinide_numeric
natglinide_numeric_z
chlorpro

In [9]:
print(dataset_df['readmitted'])

0          NO
1         >30
2          NO
3          NO
4          NO
5         >30
6          NO
7         >30
8          NO
9          NO
10        >30
11        <30
12        <30
13         NO
14        >30
15         NO
16        <30
17         NO
18        >30
19         NO
20         NO
21         NO
22         NO
23        >30
24         NO
25         NO
26         NO
27        >30
28        >30
29        >30
         ... 
101736    >30
101737     NO
101738     NO
101739     NO
101740     NO
101741     NO
101742     NO
101743     NO
101744     NO
101745     NO
101746    <30
101747    >30
101748    >30
101749     NO
101750    <30
101751     NO
101752     NO
101753     NO
101754    >30
101755    >30
101756    >30
101757     NO
101758     NO
101759     NO
101760    >30
101761    >30
101762     NO
101763     NO
101764     NO
101765     NO
Name: readmitted, Length: 101766, dtype: object


In [17]:
y = dataset_df['readmitted']
y[y == '<30'] = 0
y[y == '>30'] = 1
y[y == 'NO'] = 2
y = np.array(y)

In [18]:
y

array([2, 1, 2, ..., 0, 1, 2], dtype=object)

In [19]:
dataset_df['readmitted']

0         2
1         1
2         2
3         2
4         2
5         1
6         2
7         1
8         2
9         2
10        1
11        0
12        0
13        2
14        1
15        2
16        0
17        2
18        1
19        2
20        2
21        2
22        2
23        1
24        2
25        2
26        2
27        1
28        1
29        1
         ..
101739    2
101740    2
101741    2
101742    2
101743    2
101744    2
101745    2
101746    0
101747    1
101748    1
101749    2
101750    0
101751    2
101752    2
101753    2
101754    1
101755    1
101756    1
101757    2
101758    2
101759    2
101760    1
101761    1
101762    2
101763    2
101764    2
101765    2
<30       0
>30       1
NO        2
Name: readmitted, Length: 101769, dtype: object

In [21]:
target = y

In [24]:
predictors[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       3., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.])

In [27]:
new_df.loc[1]

metformin                   0.0
repaglinide                 0.0
nateglinide                 0.0
chlorpropamide              0.0
glimepiride                 0.0
acetohexamide               0.0
glipizide                   0.0
glyburide                   0.0
tolbutamide                 0.0
pioglitazone                0.0
rosiglitazone               0.0
acarbose                    0.0
miglitol                    0.0
troglitazone                0.0
tolazamide                  0.0
examide                     0.0
citoglipton                 0.0
insulin                     3.0
glyburide.metformin         0.0
glipizide.metformin         0.0
glimepiride.pioglitazone    0.0
metformin.rosiglitazone     0.0
metformin.pioglitazone      0.0
circulatory                 0.0
respiratory                 0.0
digestive                   0.0
diabetes                    1.0
injury                      0.0
musculoskeletal             0.0
genitourinary               0.0
neoplasms                   0.0
other   

In [28]:
predictor_df = pd.DataFrame()

In [31]:
medication_values = ['No', 'Down', 'Steady', 'Up']

# y = dataset_df['readmitted']
# y[y == '<30'] = 0
# y[y == '>30'] = 1
# y[y == 'NO'] = 2
# y = np.array(y)
# “No” = 0, “Down” = 1, “Steady” = 2, and “Up” = 3

for medication in feature_medications.columns.values:
    for index, value in enumerate(medication_values):
        predictor_df[f"{medication}_{value}"] = 
        new_df[new_df[medication] == index]

ValueError: Cannot set a frame with no defined index and a value that cannot be converted to a Series

In [252]:
import pickle
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np
from sklearn.model_selection import train_test_split

ImportError: cannot import name 'rmse' from 'sklearn.metrics' (C:\Users\aj132\Anaconda3\lib\site-packages\sklearn\metrics\__init__.py)

In [162]:
PREDICTOR_DATA_PATH = "predictor_alex_v1.pkl"
with open(PREDICTOR_DATA_PATH, 'rb') as data:
    data_dict = pickle.load(data)

In [163]:
data_dict.keys()

dict_keys(['context', 'one_hot_outcomes', 'categorical_outcomes'])

In [164]:
context_data = data_dict['context']
one_hot_outcomes = data_dict['one_hot_outcomes']
categorical_outcomes = data_dict['categorical_outcomes']

In [165]:
context_data.shape

(101766, 120)

In [166]:
combined_data

array([[0, 0, 0, ..., 1, 0, 3],
       [0, 0, 0, ..., 1, 0, 3],
       [0, 0, 0, ..., 1, 0, 3],
       ...,
       [1, 0, 0, ..., 1, 0, 2],
       [1, 0, 0, ..., 1, 0, 3],
       [1, 0, 0, ..., 1, 0, 3]])

In [167]:
combined_data = np.hstack([context_data, categorical_outcomes])
combined_data = np.array(combined_data, dtype="int")
combined_data = np.unique(combined_data, axis=0)
context_data = combined_data[:, :-1]
categorical_outcomes = combined_data[:, -1]

In [168]:
categorical_outcomes.shape

(76379,)

In [169]:
categorical_outcomes
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
categorical_outcomes_scaled = scaler.fit_transform(categorical_outcomes.reshape(-1, 1))

In [170]:
categorical_outcomes_scaled

array([[1. ],
       [1. ],
       [1. ],
       ...,
       [0.5],
       [1. ],
       [1. ]])

In [171]:
max(categorical_outcomes_scaled[0])

1.0

In [194]:
context_data.shape

(76379, 120)

In [226]:
X_train, X_test, y_train, y_test = train_test_split(context_data, categorical_outcomes_scaled, 
                                                    test_size=0.1, random_state=42)
print(f'X_train: {X_train.shape}')
print(f'X_test: {X_test.shape}')
print(f'y_train: {y_train.shape}')
print(f'y_test: {y_test.shape}')


X_test, X_val, y_test, y_val = train_test_split(X_test, y_test, 
                                                    test_size=0.2, random_state=42)
print(f'X_val: {X_val.shape}')
print(f'X_test: {X_test.shape}')
print(f'y_val: {y_val.shape}')
print(f'y_test: {y_test.shape}')


X_train: (68741, 120)
X_test: (7638, 120)
y_train: (68741, 1)
y_test: (7638, 1)
X_val: (1528, 120)
X_test: (6110, 120)
y_val: (1528, 1)
y_test: (6110, 1)


In [227]:
X_test.shape

(6110, 120)

In [228]:
y_test.shape

(6110, 1)

In [199]:
import os
os.environ["KERAS_BACKEND"]="tensorflow"
import keras
from keras.layers import Input, Dense
from keras.models import Model

In [249]:
input_layer = Input((X_train.shape[1], ))
hidden = Dense(units=64, activation="tanh")(input_layer)
# hidden = tf.keras.layers.BatchNormalization()(hidden)
hidden = Dense(units=32, activation="relu")(hidden)
# hidden = Dense(units=32, activation="tanh")(hidden)
# hidden = tf.keras.layers.BatchNormalization()(hidden)
hidden = Dense(units=16, activation="relu")(hidden)
# hidden = Dense(units=16, activation="tanh")(hidden)
# batch = tf.keras.layers.BatchNormalization()
# hidden = Dense(units=8, activation="relu")(hidden)
output = Dense(units=1, activation="sigmoid")(hidden) # CLF


model = Model(input_layer, output)

In [250]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_26 (InputLayer)        (None, 120)               0         
_________________________________________________________________
dense_80 (Dense)             (None, 64)                7744      
_________________________________________________________________
dense_81 (Dense)             (None, 32)                2080      
_________________________________________________________________
dense_82 (Dense)             (None, 16)                528       
_________________________________________________________________
dense_83 (Dense)             (None, 1)                 17        
Total params: 10,369
Trainable params: 10,369
Non-trainable params: 0
_________________________________________________________________


In [265]:
model.compile(loss=keras.losses.mean_squared_error,
              optimizer=keras.optimizers.Adam())

In [266]:
num_epochs = 100
batch_size = 128

with tf.device("CPU:0"):
    # num_samples = len(y_train)
    history = model.fit(X_train, y_train,
                        batch_size=batch_size,
                        epochs=num_epochs,
                        verbose=1,
                        validation_data=(X_test, y_test))

Train on 68741 samples, validate on 6110 samples
Epoch 1/100
68741/68741 [==============================] - 4s 54us/step - loss: 0.1226 - val_loss: 0.1256
Epoch 2/100
68741/68741 [==============================] - 2s 33us/step - loss: 0.1218 - val_loss: 0.1254
Epoch 3/100
68741/68741 [==============================] - 2s 32us/step - loss: 0.1215 - val_loss: 0.1255
Epoch 4/100
68741/68741 [==============================] - 2s 32us/step - loss: 0.1213 - val_loss: 0.1254
Epoch 5/100
68741/68741 [==============================] - 2s 32us/step - loss: 0.1211 - val_loss: 0.1250
Epoch 6/100
68741/68741 [==============================] - 2s 33us/step - loss: 0.1209 - val_loss: 0.1254
Epoch 7/100
68741/68741 [==============================] - 2s 31us/step - loss: 0.1206 - val_loss: 0.1256
Epoch 8/100
68741/68741 [==============================] - 2s 32us/step - loss: 0.1205 - val_loss: 0.1258
Epoch 9/100
68741/68741 [==============================] - 2s 32us/step - loss: 0.1202 - val_loss: 0.12

68741/68741 [==============================] - 2s 35us/step - loss: 0.1092 - val_loss: 0.1333
Epoch 78/100
68741/68741 [==============================] - 2s 35us/step - loss: 0.1092 - val_loss: 0.1331
Epoch 79/100
68741/68741 [==============================] - 2s 35us/step - loss: 0.1090 - val_loss: 0.1344
Epoch 80/100
68741/68741 [==============================] - 2s 35us/step - loss: 0.1088 - val_loss: 0.1329
Epoch 81/100
68741/68741 [==============================] - 2s 35us/step - loss: 0.1087 - val_loss: 0.1355
Epoch 82/100
68741/68741 [==============================] - 2s 35us/step - loss: 0.1086 - val_loss: 0.1358
Epoch 83/100
68741/68741 [==============================] - 2s 35us/step - loss: 0.1084 - val_loss: 0.1361
Epoch 84/100
68741/68741 [==============================] - 2s 35us/step - loss: 0.1084 - val_loss: 0.1356
Epoch 85/100
68741/68741 [==============================] - 2s 35us/step - loss: 0.1082 - val_loss: 0.1348
Epoch 86/100
68741/68741 [========================

In [81]:
y_train

array([[0. ],
       [1. ],
       [1. ],
       ...,
       [1. ],
       [0.5],
       [1. ]])

In [138]:
np.unique(np.hstack([X_train, y_train]), axis=0)

(73123, 121)

In [191]:
!pip freeze

absl-py==0.8.1
alabaster==0.7.12
altgraph==0.16.1
anaconda-client==1.7.2
anaconda-navigator==1.9.7
anaconda-project==0.8.3
asn1crypto==0.24.0
astor==0.8.0
astroid==2.2.5
astropy==3.2.1
atomicwrites==1.3.0
attrs==19.1.0
autopep8==1.4.4
awscli==1.18.50
Babel==2.7.0
backcall==0.1.0
backports.functools-lru-cache==1.5
backports.os==0.1.1
backports.shutil-get-terminal-size==1.0.0
backports.tempfile==1.0
backports.weakref==1.0.post1
beautifulsoup4==4.7.1
bitarray==0.9.3
bkcharts==0.2
bleach==3.1.0
blis==0.4.1
bokeh==1.2.0
boto==2.49.0
boto3==1.13.0
botocore==1.16.0
Bottleneck==1.2.1
cachetools==3.1.1
catalogue==1.0.0
catboost==0.20.2
certifi==2019.9.11
cffi==1.12.3
chardet==3.0.4
chart-studio==1.1.0
Click==7.0
cloudpickle==1.2.1
clyent==1.2.2
colorama==0.4.1
colorlover==0.3.0
combo==0.1.0
comtypes==1.1.7
conda==4.7.12
conda-build==3.18.8
conda-package-handling==1.3.11
conda-verify==3.4.2
confuse==1.1.0
contextlib2==0.5.5
cryptography==2.7
cufflinks==0.17.0
cycler==0.10.0
cymem==2.0.3
Cython==

In [187]:
from tensorflow.python.client import device_lib 
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 10925251297613854556
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 3144653209
locality {
  bus_id: 1
  links {
  }
}
incarnation: 11040214674259234142
physical_device_desc: "device: 0, name: GeForce GTX 1050 Ti with Max-Q Design, pci bus id: 0000:01:00.0, compute capability: 6.1"
]


In [190]:
!pip install pycaret

  Using cached tqdm-4.45.0-py2.py3-none-any.whl (60 kB)
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.32.1
    Uninstalling tqdm-4.32.1:
      Successfully uninstalled tqdm-4.32.1


You should consider upgrading via the 'c:\users\aj132\anaconda3\python.exe -m pip install --upgrade pip' command.


In [192]:
from pycaret.regression import *

In [207]:
new_model = tf.keras.models.load_model('nn_model_v2.h5')

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [208]:
new_model.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 120)]             0         
_________________________________________________________________
dense_5 (Dense)              (None, 64)                7744      
_________________________________________________________________
batch_normalization_4 (Batch (None, 64)                256       
_________________________________________________________________
dropout_4 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_6 (Dense)              (None, 32)                2080      
_________________________________________________________________
batch_normalization_5 (Batch (None, 32)                128       
_________________________________________________________________
dropout_5 (Dropout)          (None, 32)                0   

In [259]:
predictors = new_model.predict(X_test)

In [260]:
predictors.shape

(6110, 1)

In [261]:
X_test.shape

(6110, 120)

In [262]:
predictors

array([[0.7848218 ],
       [0.744847  ],
       [0.6553484 ],
       ...,
       [0.66863525],
       [0.68654996],
       [0.6474706 ]], dtype=float32)

In [263]:
np.sqrt(mean_squared_error(predictors, y_test))

0.35442249743948473

In [264]:
mean_absolute_error(predictors, y_test)

0.31283882758816406